stages:
  prepare:
    cmd: python src/prepare.py data/train.csv data/test.csv
    deps:
      - data/test.csv
      - data/train.csv
      - src/prepare.py
    params:
      - prepare.seed
      - prepare.split
    outs:
      - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
      - data/prepared
      - src/featurization.py
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - data/features
