stages:
  prepare:
    cmd: python src/prepare.py data/train.csv data/test.csv
    deps:
      - data/test.csv
      - data/train.csv
      - src/prepare.py
    params:
      - prepare.seed
      - prepare.split
    outs:
      - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
      - data/prepared
      - src/featurization.py
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - data/features
  train:
    cmd: python src/train.py data/prepared data/features model.pkl
    deps:
      - data/prepared
      - data/features
      - src/train.py
    params:
      - train.min_split
      - train.n_est
      - train.seed
    outs:
      - model.pkl
