stages:
  prepare:
    cmd: python src/prepare.py data/train.csv data/test.csv
    deps:
    - data/test.csv
    - data/train.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
